<?php

declare(strict_types=1);

// The standard the official Symfony bundles apply to their own code: the @Symfony
// rulesets shipped with PHP-CS-Fixer itself, plus strict types (not part of the
// risky set).
$finder = (new PhpCsFixer\Finder())
    ->in([__DIR__ . '/config', __DIR__ . '/src', __DIR__ . '/tests'])
    // config/reference.php is generated by Symfony (config array-shapes for an app's
    // IDE autocompletion), git-ignored, and states in its own header that bundles must
    // not rely on it. Linting it only fails the check on the machines that have it.
    ->notPath('reference.php')
;

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'declare_strict_types' => true,
        // PHP 8.3 is the composer.json floor: the syntax of that version, no older one.
        '@PHP8x3Migration' => true,
        '@PHP8x3Migration:risky' => true,
        // Keeps the tests off the PHPUnit APIs deprecated by the version the suite runs on.
        '@PHPUnit11x0Migration:risky' => true,
    ])
    ->setCacheFile(__DIR__ . '/var/cache/.php-cs-fixer.cache')
    ->setParallelConfig(PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect())
    ->setFinder($finder)
;
